name: Build and deploy docker images
on:
  push:
    branches:
      - master
    tags:
      - 'security-[0-9]+.[0-9]+.[0-9]+'

jobs:
  security:
    runs-on: ubuntu-latest
    name: Deploy Security to DockerHub
    if: startsWith(github.ref, 'refs/tags/security')
    steps:
      - uses: actions/checkout@v2
      - run: bash ./ci-scripts/docker-release.sh security ./services/security/docker/prod/Dockerfile ./services/security/package.json
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}
