name: RAD Modules CI
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    name: Compile TypeScript
    steps:
      - uses: actions/checkout@v2
      - run: npm run docker-build-watcher
      - run: npm run lint
    strategy:
      matrix:
        node-version: [16]
  security-integration:
    runs-on: ubuntu-latest
    name: Security integration
    needs:
      - setup
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2
      - run: npm run security-integration
